# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.08.03
_src_path: gh:scientific-python/cookie
backend: hatch
email: kilian.lieret@posteo.de
full_name: Kilian Lieret
license: MIT
org: gnn-tracking
project_name: ocpaper231
project_short_description: Paper for OC in mid 2023
url: https://github.com/gnn-tracking/ocpaper231
